### ISSUE TITLE
exception 'RLMException', reason: 'Index 2 is out of bounds (must be less than 0).'

### ISSUE THREAD

**Issue by vurf** [azimin/CocoaHeadsMeetupApp#323]
Ошибка возникает в struct TemplateModelCollection метод subscript. 
Как получить ошибку:
1. В анонсах выбрать первый элемент в tableView (переход во встречу)
2. Делаем свайп назад, но не до конца, как бы уходим, потом возвращаем страницу "встреча" (не закрывая ее).
3. Делаем свайп вниз, чтобы отработал tableView cellForRowAt

**Comment by smejl** [comment]
FIxed: https://github.com/cocoaheadsru/application/pull/347
