### ISSUE TITLE
Файл Storyboards.swift потерялся

### ISSUE THREAD

**Issue by NuVeS** [azimin/CocoaHeadsMeetupApp#335]
Не могу собрать проект тк нет Storyboards.swift. Видимо потерялся где-то, а найти не могу. Чего делать?

**Comment by NikoGenn** [comment]
А ты выполнял `bash firstSetup.sh`? Видимо у тебя нет Natalie

**Comment by NuVeS** [comment]
Это из лога firstSetup
==> xcrun -sdk macosx swiftc -O natalie-script.swift -o natalie.swift
Last 15 lines from /Users/NuVeS/Library/Logs/Homebrew/natalie/01.xcrun:
             FileManager
Foundation.NSFileManager:2:18: note: 'NSFileManager' was obsoleted in Swift 3
public typealias NSFileManager = FileManager
                 ^
natalie-script.swift:1183:42: error: missing argument label 'storyboardName:' in call
        file.storyboard.processStoryboard(file.storyboardName, os: os)
                                         ^
                                          storyboardName: 
natalie-script.swift:1371:16: error: instance member 'arguments' cannot be used on type 'Process'
let argument = Process.arguments[1]
               ^~~~~~~ ~~~~~~~~~
natalie-script.swift:1389:27: error: missing argument label 'storyboards:' in call
        processStoryboards(storyboardsForOS, os: os)
                          ^
                           storyboards: 

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

> 6 марта 2018 г., в 11:30, Nikita Maidanov <notifications@github.com> написал(а):
> 
> bash firstSetup.sh

**Comment by Kirillzzy** [comment]
Hello. Could you show a screenshot of an error?

**Comment by smejl** [comment]
@Kirillzzy, look console output above.

**Comment by Kirillzzy** [comment]
For me better to see colors of log. Ok, anyway, @NuVeS I need a full log.

**Comment by NuVeS** [comment]
@Kirillzzy 
Script was run...
HomeBrew:
HomeBrew checking running...
Error: /usr/local must be writable!
brew updated
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Cloning https://github.com/realm/SwiftLint.git
Updating /Library/Caches/Homebrew/swiftlint--git
==> Checking out tag 0.9.2
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Commandant'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/SWXMLHash'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Carthage/Checkouts/Nimble'
Synchronizing submodule url for 'Carthage/Checkouts/Quick'
Synchronizing submodule url for 'Carthage/Checkouts/Result'
Synchronizing submodule url for 'Carthage/Checkouts/xcconfigs'
Synchronizing submodule url for 'Externals/Nimble'
==> make prefix_install PREFIX=/usr/local/Cellar/swiftlint/0.9.2 TEMPORARY_FOLDER=/private/tmp/swiftlint-20180
Last 15 lines from /Users/NuVeS/Library/Logs/Homebrew/swiftlint/01.make:
Check dependencies
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

** CLEAN FAILED **


The following build commands failed:
	Check dependencies
	Check dependencies
	Check dependencies
	Check dependencies
(4 failures)
make: *** [clean] Error 65
make: *** Waiting for unfinished jobs....
*** Bootstrapping Carthage/Checkouts/SourceKitten...

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
==> Downloading https://github.com/krzyzanowskim/Natalie/archive/0.4.tar.gz
Already downloaded: /Library/Caches/Homebrew/natalie-0.4.tar.gz
==> xcrun -sdk macosx swiftc -O natalie-script.swift -o natalie.swift
Last 15 lines from /Users/NuVeS/Library/Logs/Homebrew/natalie/01.xcrun:
             FileManager
Foundation.NSFileManager:2:18: note: 'NSFileManager' was obsoleted in Swift 3
public typealias NSFileManager = FileManager
                 ^
natalie-script.swift:1183:42: error: missing argument label 'storyboardName:' in call
        file.storyboard.processStoryboard(file.storyboardName, os: os)
                                         ^
                                          storyboardName: 
natalie-script.swift:1371:16: error: instance member 'arguments' cannot be used on type 'Process'
let argument = Process.arguments[1]
               ^~~~~~~ ~~~~~~~~~
natalie-script.swift:1389:27: error: missing argument label 'storyboards:' in call
        processStoryboards(storyboardsForOS, os: os)
                          ^
                           storyboards: 

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-core/issues

Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Warning: carthage-0.16.2 already installed
Warning: You are using OS X 10.13.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Hook:
Hook moved
Carthage:
Please update to the latest Carthage version: 0.28.0. You currently are on 0.26.2
*** Downloading realm-cocoa.framework binary at "v3.0.1"
*** Checking out SVProgressHUD at "2.2.2"
*** Checking out Kingfisher at "4.2.0"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out realm-cocoa at "v3.0.1"
*** xcodebuild output can be found in /var/folders/c6/g8fsyhw13hs5kw8h41kzf5kw0000gq/T/carthage-xcodebuild.YMxxUJ.log
*** Building scheme "Kingfisher" in Kingfisher.xcworkspace
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
*** Building scheme "SVProgressHUD-Framework" in SVProgressHUD.xcodeproj
carthage updated
Now you should write necessary libs in Cartfile and run command 'carthage update --platform iOS'
Script was ended
Questions? Ask github.com/kirillzzy

**Comment by Kirillzzy** [comment]
I guess smth went wrong cuz of 3rd Swift version in project. We have https://github.com/cocoaheadsru/application/pull/316, try to repeat your actions after merging this pull request (I look forward to @smejl review this pull request 😄).

I don't close this issue now, repeat after merging, we'll do it in the nearest future. Thanks.

**Comment by Kirillzzy** [comment]
@NuVeS try to pull & repeat your actions)

**Comment by ichina** [comment]
@Kirillzzy do you have any ideas why do `Natalie Build Phase` located BELOW `Compile Source Phase`? 
<img width="709" alt="screen shot 2018-03-07 at 17 49 26" src="https://user-images.githubusercontent.com/1898138/37098982-4ea4eaf4-2230-11e8-8154-949047867dd8.png">
As i understand, you need to move `Natalie Build Phase` above `Complile Source Phase` for conforming chronology

**Comment by Kirillzzy** [comment]
@ichina Try to change the location. It's good prediction.

**Comment by ichina** [comment]
added to my [PR](https://github.com/cocoaheadsru/application/pull/336)
