### ISSUE TITLE
Видео встречи

### ISSUE THREAD

**Issue by NuVeS** [azimin/CocoaHeadsMeetupApp#341]
Хочу добавить возможность просмотра видео из [этого таска](https://trello.com/c/RqyrimV3). Но не понимаю как это должно выглядеть в приложении и как приходит видео с сервера

**Comment by smejl** [comment]
У каждого `SpeechEntity` есть `contents`. Это список объектов `SpeechContentEntity`. Сейчас мы с сервера можем отправлять видео и слайды. 
Нужно зафейкать респонс. И для типа SpeechContentType.video открывать экран с просмотром и возможностью скачать видео.
